-- TO ADD A DEBUGER FOR A LANGUAGE YOU HAVE TO GO TO THIS WIKI — https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation
-- CHOOSE A LANGUAGE AND GO ACCORDING TO A GUIDE
-- YOU MAY HAVE TO ADD DEPENDENCIES AND DON'T FORGET TO REQUIRE THEM IN CONFIG = FUNCTION()
return {
	-- "mfussenegger/nvim-dap",
	-- dependencies = {
	-- 	"rcarriga/nvim-dap-ui",
	-- },
	-- config = function()
	-- 	local dap = require("dap")
	-- 	local dapui = require("dapui")
	--
	-- 	require("dapui").setup()
	--
	-- 	dap.listeners.before.attach.dapui_config = function()
	-- 		dapui.open()
	-- 	end
	-- 	dap.listeners.before.launch.dapui_config = function()
	-- 		dapui.open()
	-- 	end
	-- 	dap.listeners.before.event_terminated.dapui_config = function()
	-- 		dapui.close()
	-- 	end
	-- 	dap.listeners.before.event_exited.dapui_config = function()
	-- 		dapui.close()
	-- 	end
	--
	-- 	dap.adapters.gdb = {
	-- 		type = "executable",
	-- 		command = "gdb",
	-- 		args = { "-i", "dap" },
	-- 	}
	--
	-- 	dap.configurations.cpp = {
	-- 		{
	-- 			name = "Launch",
	-- 			type = "gdb",
	-- 			request = "launch",
	-- 			program = function()
	-- 				return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
	-- 			end,
	-- 			cwd = "${workspaceFolder}",
	-- 			stopAtBeginningOfMainSubprogram = false,
	-- 		},
	-- 	}
	--
	-- 	vim.keymap.set("n", "<leader>dt", dap.toggle_breakpoint, {})
	-- 	vim.keymap.set("n", "<leader>dc", dap.continue, {})
	-- end,
}
